/**
 * Core types for Docusaurus2PDF
 */

// Site and navigation types
export interface Site {
  Root: string;
  DocsDir: string;
  Sidebars: Category[];
  Pages: DocPage[];
  Config?: SiteConfig;
  DefaultLocale?: string;
  /** True when the site config references remark-math/KaTeX. */
  UsesMath?: boolean;
}

export interface SiteConfig {
  Title: string;
  Tagline?: string;
  URL?: string;
}

export interface Category {
  Type: string;
  Label: string;
  Items: SidebarItem[];
  Link?: Link;
}

export interface SidebarItem {
  Type: string;
  ID?: string;
  Label?: string;
  Items?: SidebarItem[];
  /** For type 'autogenerated': directory the items are generated from. */
  DirName?: string;
  Link?: Link;
}

/** Flattened, ordered document outline derived from the sidebars. */
export interface OrderedEntry {
  Type: 'category' | 'doc';
  /** Category heading text (Type === 'category'). */
  Label?: string;
  /** The document (Type === 'doc'). */
  Doc?: DocPage;
  /** 1-based outline depth; 1 maps to \section. */
  Level: number;
}

export interface Link {
  Type: string;
  ID: string;
}

export interface DocPage {
  Path: string;
  ID: string;
  Title: string;
  Content: string;
  Language: string;
  Frontmatter: Record<string, unknown>;
}

// LaTeX language configuration
export interface LanguageConfig {
  BabelLang: string;
  FontEnc: string;
  Packages: string[];
  Vlna: boolean;
  XeTeX: boolean;
}

export const SupportedLanguages: Record<string, LanguageConfig> = {
  cs: {
    BabelLang: 'czech',
    FontEnc: 'T1',
    Packages: [],
    Vlna: true,
    XeTeX: false,
  },
  en: {
    BabelLang: 'english',
    FontEnc: 'T1',
    Packages: [],
    Vlna: false,
    XeTeX: false,
  },
  de: {
    BabelLang: 'ngerman',
    FontEnc: 'T1',
    Packages: [],
    Vlna: false,
    XeTeX: false,
  },
  sk: {
    BabelLang: 'slovak',
    FontEnc: 'T1',
    Packages: [],
    Vlna: true,
    XeTeX: false,
  },
};

// Parser types
export interface ParsedPage {
  Title: string;
  Content: string;
  Frontmatter: Record<string, unknown>;
  PlantUMLDiagrams: Array<{ hash: string; code: string }>;
  MermaidDiagrams: Array<{ hash: string; code: string }>;
  /** Remote image URLs referenced by the page; the renderer downloads them. */
  RemoteImages?: Array<{ url: string; filename: string }>;
}

export interface MDXParserOptions {
  stripManualNumbering?: boolean;
  convertEmoji?: boolean;
  useEmojiCommands?: boolean;
  suppressCaptionNumbers?: boolean;
  /** Document language; enables language-specific typography (vlna for cs/sk). */
  language?: string;
  /**
   * Canonical keys of all documents in the build (MDXParser.canonicalDocKey).
   * When set, cross-document links resolve to internal \hyperref targets;
   * unresolvable links degrade to plain text instead of dead URLs.
   */
  knownDocs?: Set<string>;
  /**
   * Parse $...$/$$...$$ as math. Should mirror whether the Docusaurus site
   * has remark-math/KaTeX configured; otherwise "$5 and $10" prose would be
   * swallowed as a formula.
   */
  enableMath?: boolean;
}

// Renderer types
export interface RendererOptions {
  OutputDir: string;
  Engine: 'lualatex' | 'xelatex' | 'pdflatex' | 'tectonic';
  Sections?: string[];
  StripManualNumbering?: boolean;
  ConvertEmoji?: boolean;
  SuppressCaptionNumbers?: boolean;
  SkipDiagrams?: boolean;
}

// LaTeX generator types
export interface LatexGeneratorOptions {
  Engine: 'lualatex' | 'xelatex' | 'pdflatex' | 'tectonic';
  Title: string;
  Language: string;
  Date: string;
  Author?: string;
}

export interface DocumentSection {
  Title: string;
  Content: string;
  Level: number;
  /** Canonical doc key; emitted as \label{doc:<key>} for cross-doc links. */
  LabelKey?: string;
  PlantUMLDiagrams?: Array<{ hash: string; code: string }>;
  MermaidDiagrams?: Array<{ hash: string; code: string }>;
}

// CLI types
export interface CLIOptions {
  input: string;
  output: string;
  engine: 'lualatex' | 'xelatex' | 'pdflatex' | 'tectonic';
  single: boolean;
  perLanguage: boolean;
  texOnly: boolean;
  compileOnly: boolean;
  docker: boolean;
  stripNumbering: boolean;
  convertEmoji: boolean;
  suppressCaptionNumbers: boolean;
  sections?: string;
}

// Plugin types
export interface PluginOptions {
  outputDir?: string;
  engine?: 'lualatex' | 'xelatex' | 'pdflatex' | 'tectonic';
  sections?: string[];
}
